# -*- coding: utf-8 -*-
"""FileFormatConversion.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1hOX9Qz9puhhGdNB7Hb1Wn1FxVIaMEBwe
"""

from google.colab import files
import pandas as pd


# user input
choices = input('Choose conversion format: \n 1 - CSV to Excel \n 2 - Excel to CSV \n')

print('Please upload your file: ')
uploaded_file = files.upload()
file_name = next(iter(uploaded_file))

# csv to excel
if choices == '1':
  output_file = input("Enter new file name: \n")
  data = pd.read_csv(file_name)
  data.to_excel(output_file, index = False)
  print("Conversion completed.")
  files.download(output_file)

# excel to csv
elif choices == '2':
  output_file = input("Enter new file name: \n")
  data = pd.read_excel(file_name)
  data.to_csv(output_file, index = False)
  print("Conversion completed.")
  files.download(output_file)

else:
  print("Invalid Choice!")